env:
  browser: true
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "plugin:boundaries/recommended"
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
plugins:
  - "@typescript-eslint"
  - boundaries
settings:
  import/resolver:
    - typescript:
        - alwaysTryTypes: true

  boundaries/elements:
    - type: app
      pattern:
        - src/app/*
      capture:
        - segment

    - type: routes
      pattern:
        - src/routes/*

    - type: widgets
      pattern:
        - src/widgets/*
      capture:
        - slice

    - type: features
      pattern:
        - src/features/*/*/*
      capture:
        - group
        - feature
        - segment

    - type: entities
      pattern:
        - src/entities/*/*
      capture:
        - entity
        - segment

    - type: shared
      pattern:
        - src/shared/*
      capture:
        - segment

rules:
  boundaries/element-types:
    - 2
    - default: disallow
      rules:
        - from:
            - app
          allow:
            - app
            - widgets
            - routes
            - features
            - entities
            - shared

        - from:
            - widgets
          allow:
            - features
            - entities
            - shared

        - from:
            - routes
          allow:
            - widgets
            - features
            - entities
            - shared

        - from:
            - features
          allow:
            - features
            - entities
            - shared

        - from:
            - entities
          allow:
            - entities
            - shared

        - from:
            - shared
          allow:
            - shared

  boundaries/entry-point:
    - 2
    - default: disallow
      rules:
        - target:
            - app
            - widgets
            - features
            - entities
            - shared
          allow:
            - index.ts
